### ISSUE TITLE
add indicator to powerline when timekeeper started

### ISSUE THREAD

**Issue by khmelevskii** [PAntoine/TimeKeeper#1]
its posible?

**Comment by PAntoine** [comment]
What start time? The time you loaded the browser, or the time the project started?

I think they should both be possible. Can generate a function that will return a string and you can add that to the statusline function.

I don't use powerline ,but looking at the docs it seems that it can take a function that returns a string.

Is that what you need?

**Comment by khmelevskii** [comment]
It would be perfect to implement two useful functions:
1) returns the beginning time of job
2) returns the amount of time spent on the job execution

**Comment by PAntoine** [comment]
Ok. 
"TimeKeeper_GetCurrentJobString()"

Will return: <project>.<job>#dd:hh:mm
which is the working time that has been spent on the current job.

I can add a function to return the start time of the job, I am storing that, and I can add a function to return the difference from that time to now. I'll also add a total for the project (all jobs) as I have that information as well.

**Comment by PAntoine** [comment]
Added new status functions.
See the docs, hopefully these are what you need.
