### ISSUE TITLE
dont work with MacVim

### ISSUE THREAD

**Issue by mhhf** [PAntoine/TimeKeeper#2]
It works fine in my command line vim, but not in MacVim.

Its listed under the loaded scripts (:scriptnames) and I have access to the Variables (:echo g:TimeKeeperAwayTimeSec) but I can't call any functions and there aren't any listed under ":function".

I have OSX 10.8.1 with MacVim 7.3.806

**Comment by PAntoine** [comment]
OK, I don't have access to a Mac, only Linux and Windows.

But, can you try the following:
:call TimeKeeper_StartTracking()
:echo TimeKeeper_GetCurrentJobString()

This is just to test to see if it is starting up. You should get a question asking you the following:
"Please supply TimeKeeper timesheet filename: " 

(if you have not been asked this before)
This should then create a .timekeeper.tmk file where you ask it to (leave a default for now).

**Comment by mhhf** [comment]
":call TimeKeeper_StartTracking()" gives the output "E117: Unknown function: TimeKeeper_StartTracking"
":echo TimeKeeper_GetCurrentJobString()" gives the output 
"E117: Unknown function: TimeKeeper_StartTracking
E15: Invalid expression: TimeKeeper_GetCurrentJobString()"

which is strange, because when i type ":echo g:TimeKeeperFileName" it gives the output "/Users/mhhf/.timekeeper.tmk"

**Comment by PAntoine** [comment]
Ok, in line 33 of plugin/TimeKeeper.vim

can you change the line to
    if !exists("s:TimeKeeperPlugin") || 1

Then restart vim, then can you do the above tests again, just want to know if the guard variable is causing a problem.

Also, can you do `:version` and see if "+clientserver" is set. I do runtime check, but never run it on an instance with it turned off.

Also, can you if the above do nothing can you do the following (if it is supported on MacVim):
    gvim vim -V9myVimLog

And send me the log, I STRONGLY suggest that you sanitise this file for anything sensitive in it before you send it. I'll have a look to see if I can find anything.

**Comment by mhhf** [comment]
indeed the error was caused by the guard.

I changed the lines in 92:

```
if exists("s:TimeKeeperPlugin")
 finish
endif
```

and it works well.

tank you for this great plugin and your support!

**Comment by mhhf** [comment]
there is also a problem with line 125 of the "prepare-commit-msg" file:

```
line=${project:1:-1}
```

my bash seems to have a problem with a negative length. I get the following error:

   .git/hooks/prepare-commit-msg: line 125: -1: substring expression < 0

im using `GNU bash, version 3.2.48(1)-release`

this works well: `line=${project:1:${#project}-2}`

**Comment by PAntoine** [comment]
Ok, thanks I'll add these to the next release.

**Comment by PAntoine** [comment]
version 2.0.1 released with this fixes in.
